CREATE DATABASE IF NOT EXISTS club;
USE club;

CREATE TABLE IF NOT EXISTS Users
(
    PkUser INT NOT NULL AUTO_INCREMENT,
    User VARCHAR(50) NOT NULL DEFAULT "",
    Pass VARCHAR(50) NOT NULL DEFAULT "",
    PRIMARY KEY (PkUser)
);
INSERT INTO Users (User, Pass) VALUES
('admin','admin')